autograding:
  - name: Run Pytest Tests
    setup: |
      pip install -r requirements.txt
      docker compose up -d  # Start Spring Boot in the background
      sleep 15  # Wait for Spring Boot to be ready (adjust timing if needed)
    run: pytest tests/ --tb=short --maxfail=5 --disable-warnings --json-report --json-report-file=report.json
    timeout: 120
    points: 10
    output: all
